lab50:
  files:
    - !exclude "*"
    - !include "Exceptron.class"
    - !include "SelectFrom.java"
    - !include "SelectFromTest.java"
    - !include "SelectFromTest.class"
    - !include "SuperCoolException.java"
    - !include "SuperCoolException.class"
    - !include "ExceptronTest.class"
    - !include "ExceptronPlatform.java"
    
  window:
    - editor
    - readme
    - terminal
