lab50:
  files:
    - !exclude "*"
    - !include "Student.java"
    - !include "Person.java"
    - !include "Lecturer.java"
    - !include "Professor.java"
    
  window:
    - editor
    - readme
    - terminal