check50: 
  dependencies:
    - check50-java
    - check50-junit

  files: &check50_files
    - !exclude "*"
    - !include "Book.java"
    - !include "CassetteException.java"
    - !include "Press.java"
    - !include "VendingMachine.java"
    

submit50:
  files: *check50_files
