check50:
  dependencies:
    - check50-java
    - check50-junit
  files:
    - !exclude "*"
    - !include "VGather.java"
    - !include "Student.java"
    

submit50:
  slug: "liv-ac-uk/comp122/2021/objects"
  files:
    - !exclude "*"
    - !include "VGather.java"
    - !include "Student.java"
