check50:
  dependencies:
    - check50-java
    - check50-junit
  files: &check50_files
    - !exclude "*"
    - !include "IOLabPartTwo.java"


submit50:
  slug: "liv-ac-uk/comp122/2021/io"
  files: *check50_files
