check50:
  dependencies:
    - check50-java
    - check50-junit
  files: &check50_files
    - !exclude "*"
    - !include "SelectFrom.java"
    - !include "ExceptronPlatform.java"


submit50:
  slug: "liv-ac-uk/comp122/2021/exceptions"
  files: *check50_files
