check50:
  dependencies:
    - check50-java
    - check50-junit
  files:
    - !exclude "*"
    - !include "CShanty.java"
    - !include "Factorial.java"
    - !include "Largest.java"
    


submit50:
  slug: "liv-ac-uk/comp122/2021/arrayLoops"
  files:
    - !exclude "*"
    - !include "CShanty.java"
    - !include "Factorial.java"
    - !include "Largest.java"
    
