lab50:
  files:
    - !exclude "*"
    - !include SpamEmail.java
    - !include SpamFrom.java
    - !include SpamSender.java
    - !include Dictionary.txt
    - !include Spam.txt
    - !include Rebel.java
    
  window:
    - editor
    - readme
    - terminal