check50:
  dependencies:
    - check50-java
    - check50-junit
  files:
    - !exclude "*"
    - !include "Lecturer.java"
    - !include "Person.java"
    - !include "Professor.java"
    - !include "Student.java"

submit50:
  slug: "liv-ac-uk/comp122/2021/inheritance"
  files:
    - !exclude "*"
    - !include "Lecturer.java"
    - !include "Person.java"
    - !include "Professor.java"
    - !include "Student.java"