check50:
  dependencies:
    - check50-java
    - check50-junit
  files:
    - !exclude "*"
    - !include "Student.java"

submit50:
  slug: "liv-ac-uk/comp122/2021/constructors"
  files:
    - !exclude "*"
    - !include "Student.java"
