check50:
  dependencies:
    - check50-java
  files:
    - !exclude "*"
    - !include "Declarations.java"
    - !include "FPTestApp.java"
    - !include "SimpleCircle.java"
    - !include "Pythagoras.java"
    - !include "Cosines.java"

submit50:
  slug: "liv-ac-uk/comp122/2021/variables"
  files:
    - !exclude "*"
    - !include "Declarations.java"
    - !include "FPTestApp.java"
    - !include "SimpleCircle.java"
    - !include "Pythagoras.java"
    - !include "Cosines.java"
