check50:
  dependencies:
    - check50-java
    - check50-junit
    - check50-checkstyle
  files: &check50_files
    - !exclude "*"
    - !include "Caesar.java"
    - !include "Brutus.java"

submit50:
  files: *check50_files
