check50:
  dependencies:
    - check50-java

  files:
    - !exclude "*"
    - !include "Rebel.java"
    - !include "Spam.java"

    


submit50:
  slug: "liv-ac-uk/comp122/2021/regex"
  files:
    - !exclude "*"
    - !include "Rebel.java"
    - !include "Spam.java"
    
