check50:
  dependencies:
    - check50-java
    - check50-junit

  files: &check50_files
    - !exclude "*"
    - !include "Cipher.java"
    - !include "Substitution.java"
    - !include "MonoAlphaSubstitution.java"
    - !include "Caesar.java"
    - !include "Vigenere.java"

submit50:
  files: *check50_files

